info:
  app:
    name: KTT IGW Project
    version: ${project.version}
spring:
  application:
    name: IGW
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
    gzip:
      enabled: false
logging:
  config: classpath:logback.xml
datasource:
  datasource1:
    url: jdbc:h2:mem:testdb1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
    initial: true
    validationQuery: SELECT 1
    maxTotal: 2
    maxIdle: 1
    initialSize: 1
    defaultAutoCommit: false
  datasource2:
    url: jdbc:h2:mem:testdb2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
    initial: true
    validationQuery: SELECT 1
    maxTotal: 2
    maxIdle: 1
    initialSize: 1
    defaultAutoCommit: false

